export const FETCH_SHOPS_START = 'FETCH_SHOPS_START';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAIL = 'FETCH_SHOPS_FAIL';
export const HANDLE_FORM_INPUT_CHANGE = 'HANDLE_FORM_INPUT_CHANGE';
export const HANDLE_FORM_INPUT_ADDRESS_CHANGE = 'HANDLE_FORM_INPUT_ADDRESS_CHANGE';
export const HANDLE_FORM_INPUT_ADDRESS_COORDINATES_CHANGE = 'HANDLE_FORM_INPUT_ADDRESS_COORDINATES_CHANGE';
export const ADD_SHOP_START = 'ADD_SHOP_START';
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS';
export const ADD_SHOP_FAIL = 'ADD_SHOP_FAIL';

export const LOOKUP_POSTCODE_START = 'LOOKUP_POSTCODE_START';
export const LOOKUP_POSTCODE_SUCCESS = 'LOOKUP_POSTCODE_SUCCESS';
export const HANDLE_FORM_INPUT_POSTCODE_CHANGE = 'HANDLE_FORM_INPUT_POSTCODE_CHANGE';
