export const FETCH_SHOPS_START = 'FETCH_SHOPS_START';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAIL = 'FETCH_SHOPS_FAIL';
export const ADD_SHOP_NAME_CHANGED = 'ADD_SHOP_NAME_CHANGED';
export const ADD_SHOP_ADDRESS_CHANGED = 'ADD_SHOP_ADDRESS_CHANGED';