export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const HANDLE_FORM_INPUT_CHANGE = 'HANDLE_FORM_INPUT_CHANGE';
export const HANDLE_FORM_INPUT_ADDRESS_CHANGE = 'HANDLE_FORM_INPUT_ADDRESS_CHANGE';
export const HANDLE_FORM_INPUT_ADDRESS_COORDINATES_CHANGE = 'HANDLE_FORM_INPUT_ADDRESS_COORDINATES_CHANGE';

export const FETCH_SHOPS_START = 'FETCH_SHOPS_START';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAIL = 'FETCH_SHOPS_FAIL';

export const FETCH_SHOP_START = 'FETCH_SHOP_START';
export const FETCH_SHOP_SUCCESS = 'FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAIL = 'FETCH_SHOP_FAIL';

export const ADD_SHOP_START = 'ADD_SHOP_START';
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS';
export const ADD_SHOP_FAIL = 'ADD_SHOP_FAIL';

export const HANDLE_FORM_INPUT_POSTCODE_CHANGE = 'HANDLE_FORM_INPUT_POSTCODE_CHANGE';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const LOOKUP_POSTCODE_START = 'LOOKUP_POSTCODE_START';
export const LOOKUP_POSTCODE_SUCCESS = 'LOOKUP_POSTCODE_SUCCESS';
export const LOOKUP_COORDINATES_START = 'LOOKUP_COORDINATES_START';
export const LOOKUP_COORDINATES_SUCCESS = 'LOOKUP_COORDINATES_SUCCESS';
export const LOOKUP_COORDINATES_FAIL = 'LOOKUP_COORDINATES_FAIL';

export const FIND_SHOPS_START = 'FIND_SHOPS_START';
export const FIND_SHOPS_SUCCESS = 'FIND_SHOPS_SUCCESS';
export const FIND_SHOPS_FAIL = 'FIND_SHOPS_FAIL';

export const UPDATE_RATING = 'UPDATE_RATING';

export const ADD_RATING_START = 'ADD_RATING_START';
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS';
export const ADD_RATING_FAIL = 'ADD_RATING_FAIL';
